### ISSUE TITLE
Can't access /admin after a fresh install

### ISSUE THREAD

**Issue by Daktyl198** [rs1703/Kasen#3]
For what it's worth, I'm sure it's something I've done wrong. I've followed the instructions to set Kasen up on a server running Ubuntu 22.04 LTS and it seems to be working perfectly except for the fact that the `/admin` path just leads to a 404 page, and so we can't actually upload anything to it. All other paths work fine.

**Comment by rs1703** [comment]
Seems I put the wrong path in the README.md, the correct path is `/manage`. Sorry about that!

**Comment by Daktyl198** [comment]
Yeah, I was just about to close the issue. I checked the code and saw the correct path already. Thanks for replying so fast though!
